### ISSUE TITLE
Feature: Setting page/route bound (temporary) tags.

### ISSUE THREAD

**Issue by Eraldo** [jenbuzz/ngx-metafrenzy#24]
Hello and first of all: I want to thank you for providing this library to assist with meta tags management.  🙏🏽

More specifically what I would like to see: Intended usage description when leaving a page.

I do understand how to set some tags with the use of the provided service.
However I wonder how to deal with navigating away from the current page.
The way I understand it, I would still end up keeping the last set tags.
Is there a best practice of how to only apply the tags when I'm actually on the page where it applies?

Maybe even something that we can put in the about description or bake into the library itself?
Any ideas or recommendations of how to deal with that?

**Comment by jenbuzz** [comment]
Not sure I understand your issue. Could you provide an example?

**Comment by Eraldo** [comment]
> Not sure I understand your issue. Could you provide an example?

If I enter `PageB` and this page sets the title to "Page B", and then I quit the page => going back to where I came from -- let's say `PageA` which did not set a title, then I would end up on `PageA` with a title of "Page B".
What I want that the changes are only in effect on that page. ;)

Does that already help clarify a bit?

**Comment by jenbuzz** [comment]
In the latest version you can try to add this to your module: "canDeactivate: [MetafrenzyGuard]".
It will try to to do a reset of metatags when navigating between routes. It can't reset metatags that were set using the service class.
If this won't solve this issue, I would recommend subscribing to router events and use the service class to call remove (tag or link) function.
There is some more information on this in the README and in the projects demo app.
