### ISSUE TITLE
Incompatible with typescript strictNullChecks

### ISSUE THREAD

**Issue by mpetito-envative** [jenbuzz/ngx-metafrenzy#5]
If you configure an angular project's typescript options with `strict` or `strictNullChecks`, then you run into compilation issues with several of metafrenzy's interface definitions.  For ex., 

> error TS2411: Property 'charset' of type 'string | undefined' is not assignable to string index type 'string'.

This applies to all of the properties in the `LinkDefinition` and `OpenGraph` interfaces.

Also it seems that if you enable `strictNullChecks` for this project there are a few potential bugs identified in `MetafrenzyService`.

**Comment by jenbuzz** [comment]
Thank you for pointing this out. A fix was included in a recent release.
